library(RColorBrewer)
library(viridis)
library(colorspace)
library(scico)
library(readxl)
library(reshape2)
library(ggplot2)
library(ggpubr)
library(grid)
library(scales)

# setwd local
setwd("C:/Users/Kaifs/OneDrive/Documents/dropbox_penn/Dropbox/GitHub/PrjCEC/")

# File names
bl_main_save <- TRUE
verbose <- TRUE
spt_path_res <- file.path("res", "res_atrisk", fsep = .Platform$file.sep)
# Input data file, generated by `R-script/tabfig_1_mean_child/ffs_pirecec_tf_mean_child_csv.R`
spn_path <- file.path(spt_path_res, "fig_a_data.csv", fsep = .Platform$file.sep)
dat_lvl_diff_1990_2020 <- read_csv(spn_path)

# change_path <- file.path(spt_path_res, "tab_b_change_data.csv", fsep=.Platform$file.sep)
# dat_lvl_change_1990_2020 <-read_csv(change_path)

# diff_2020_1990 <-
# read_excel("c:/users/kaifs/onedrive/documents/dropbox_penn/dropbox/pire/team/kai_feng/cec_results/res_b_childrenatrisk/plot_data.xlsx", sheet = "diff_2020_1990")
# dat1990 <-
# read_excel("C:/Users/Kaifs/OneDrive/Documents/dropbox_penn/Dropbox/PIRE/team/kai_feng/cec_results/res_b_childrenatrisk/plot_data.xlsx", sheet = "1990")
# dat2020 <-
# read_excel("C:/Users/Kaifs/OneDrive/Documents/dropbox_penn/Dropbox/PIRE/team/kai_feng/cec_results/res_b_childrenatrisk/plot_data.xlsx", sheet = "2020")

dat1990 <- 
  dat_lvl_diff_1990_2020 %>%
  filter(stats == "cdf_comp", year == 1990) %>%
  select(-year,-stats,-utci_20,-utci_21,-utci_22,-utci_23,-utci_24,-utci_25,
         -utci_27,-utci_29,-utci_31,-utci_33,-utci_35,-utci_37,-utci_39) %>%
  pivot_longer(2:9,names_to = "utci_thres", values_to = "value") %>%
  filter(!share_time %in% c(0.08, 0.16, 0.24, 0.32)) %>%
  mutate(utci = c(rep(seq(26,40,2),5)),
         type = "2020") %>%
  filter(utci!=40)

dat2020 <- dat_lvl_diff_1990_2020 %>%
    filter(stats == "cdf_comp", year == 2020) %>%
  select(-year,-stats,-utci_20,-utci_21,-utci_22,-utci_23,-utci_24,-utci_25,
         -utci_27,-utci_29,-utci_31,-utci_33,-utci_35,-utci_37,-utci_39) %>%
  pivot_longer(2:9,names_to = "utci_thres", values_to = "value") %>%
  filter(!share_time %in% c(0.08, 0.16, 0.24, 0.32)) %>%
  mutate(utci = c(rep(seq(26,40,2),5)),
         type = "2020") %>%
  filter(utci!=40)
  
diff_2020_1990 <- dat_lvl_diff_1990_2020 %>%
  filter(stats == "cdf_comp_diff") %>%
  select(-year,-stats,-utci_20,-utci_21,-utci_22,-utci_23,-utci_24,-utci_25,
         -utci_27,-utci_29,-utci_31,-utci_33,-utci_35,-utci_37,-utci_39) %>%
  pivot_longer(2:9,names_to = "utci_thres", values_to = "value") %>%
  filter(!share_time %in% c(0.08, 0.16, 0.24, 0.32)) %>%
  mutate(utci = c(rep(seq(26,40,2),5)),
         type = "2020 - 1990") %>%
  filter(utci!=40)

# dat_change_1990_2020 <- dat_lvl_change_1990_2020 %>%
#   filter(stats == "cdf_comp_diff_ratio") %>%
#   filter(utci_thres %in% c(26)) %>% 
#   select(-year,-shrtime_8,-shrtime_16,-shrtime_24,-shrtime_32) %>%
#   pivot_longer(3:7,names_to = "share_time",values_to = "value") %>%
#   rename(utci=utci_thres) %>%
#   mutate(type = "2020/1990")


# dat_change_1990_2020 %>%
#   ggplot(aes(x = utci, y = share_time, fill = value*100)) +
#   geom_tile() +
#   geom_text(aes(label = sprintf("%.1f%%", value*100)), size = 4, alpha=0.7) +
#   scale_fill_gradient2(mid = "#FBFEF9", low = "#A63446", high = "#0C6291") +
#   # scale_fill_gradientn(colors = colorRampPalette(brewer.pal(9, "YlOrRd"))(100))+
#   # scale_fill_gradientn(colors = rev(sequential_hcl(100,h = c(0, 0))))+
#   theme_classic() +
#   scale_y_reverse(breaks = seq(0.04, 0.36, 0.08),
#                   labels = function(x) paste("≥", percent_format()(x))) +
#   theme(
#     text = element_text(size = 13),
#     axis.text.y = element_text(size = 13),
#     axis.text.x = element_text(size = 13),
#     legend.text = element_text(size = 12),
#     legend.title = element_text(size = 13)
#   ) +
#   labs(x = " ", y = "At least y% of time\n", fill = "x%(cell) of cihldren") +
#   theme(legend.position = "") +
#   scale_x_continuous(
#     breaks = seq(26, 32, 1),
#     labels = function(x) paste("≥", x, " °C")
#   ) +
#   ggtitle("Panel C: Percentage 2020 - Percentage 1990")
  

dat <- rbind(diff_2020_1990, dat1990, dat2020)

fig1 <- ggplot(diff_2020_1990, aes(x = utci, y = share_time, fill = value*100)) +
    geom_tile() +
  geom_text(data = subset(diff_2020_1990, value != 0),
            aes(label = sprintf("%.1f%%", value * 100)),
            size = 5, alpha = 0.7) +
    scale_fill_gradient2(mid = "#FBFEF9", low = "#A63446", high = "#0C6291") +
    # scale_fill_gradientn(colors = colorRampPalette(brewer.pal(9, "YlOrRd"))(100))+
    # scale_fill_gradientn(colors = rev(sequential_hcl(100,h = c(0, 0))))+
    theme_classic() +
    scale_y_reverse(breaks = seq(0.04, 0.36, 0.08),
                    labels = function(x) paste("≥", percent_format()(x))) +
    theme(
        text = element_text(size = 13),
        axis.text.y = element_text(size = 13),
        axis.text.x = element_text(size = 13),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 13)
    ) +
    labs(x = " ", y = "At least y% of time\n", fill = "x%(cell) of cihldren") +
    theme(legend.position = "") +
  scale_x_continuous(
    breaks = seq(26, 40, 2),
    labels = function(x) paste("≥", x, " °C")
  ) +
  ggtitle("")
fig1

fig2 <- ggplot(dat1990, aes(x = utci, y = share_time, fill = value*100)) +
  geom_tile() +
  geom_text(data = subset(dat1990, value != 0),
            aes(label = sprintf("%.1f%%", value * 100)),
            size = 5, alpha = 0.7) +
  scale_fill_gradient2(mid = "#FBFEF9", low = "#0C6291", high = "#A63446") +
  # scale_fill_gradientn(colors = colorRampPalette(brewer.pal(9, "YlOrRd"))(100))+
  # scale_fill_gradientn(colors = rev(sequential_hcl(100,h = c(0, 0))))+
  theme_classic() +
  scale_y_reverse(breaks = seq(0.04, 0.36, 0.08),
                  labels = function(x) paste("≥", percent_format()(x))) +
  theme(
    text = element_text(size = 13),
    axis.text.y = element_text(size = 13),
    axis.text.x = element_text(size = 13),
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 13)
  ) +
  labs(x = " ", y = "At least y% of time\n", fill = "x%(cell) of cihldren") +
  theme(legend.position = "") +
  scale_x_continuous(
    breaks = seq(26, 40, 2),
    labels = function(x) paste("≥", x, " °C")
  ) +
  ggtitle("")
fig2

fig3 <- ggplot(dat2020, aes(x = utci, y = share_time, fill = value*100)) +
  geom_tile() +
  geom_text(data = subset(dat2020, value != 0),
            aes(label = sprintf("%.1f%%", value * 100)),
            size = 5, alpha = 0.7) +
  scale_fill_gradient2(mid = "#FBFEF9", low = "#0C6291", high = "#A63446") +
  # scale_fill_gradientn(colors = colorRampPalette(brewer.pal(9, "YlOrRd"))(100))+
  # scale_fill_gradientn(colors = rev(sequential_hcl(100,h = c(0, 0))))+
  theme_classic() +
  scale_y_reverse(breaks = seq(0.04, 0.36, 0.08),
                  labels = function(x) paste("≥", percent_format()(x))) +
  theme(
    text = element_text(size = 13),
    axis.text.y = element_text(size = 13),
    axis.text.x = element_text(size = 13),
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 13)
  ) +
  labs(x = " ", y = "At least y% of time\n", fill = "x%(cell) of cihldren") +
  theme(legend.position = "") +
  scale_x_continuous(
    breaks = seq(26, 40, 2),
    labels = function(x) paste("≥", x, " °C")
  ) +
  ggtitle("")
fig3



# ggplot(dat, aes(x = Column, y = Row, fill = value)) +
#     geom_tile() +
#     geom_text(aes(label = sprintf("%.2f%%", value)), size = 4) +
#     # scale_fill_gradient2(mid="#FBFEF9",low="#0C6291",high="#A63446") +
#     scale_fill_gradientn(colors = colorRampPalette(brewer.pal(9, "YlOrRd"))(100)) +
#     # scale_fill_gradientn(colors = rev(sequential_hcl(100,h = c(0, 0))))+
#     facet_wrap(~type, scales = "free", ncol = 1) +
#     theme_classic() +
#     scale_y_reverse() +
#     theme(
#         # panel.border = element_blank(),
#         panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         axis.line = element_line(colour = "black"),
#         text = element_text(size = 13),
#         axis.text.y = element_text(size = 13),
#         axis.text.x = element_text(size = 13),
#         legend.text = element_text(size = 12)
#     ) +
#     labs(x = "UTCI", y = "Minimum Annual Share of Children's Hours", fill = "Percentage of Children (%)") +
#     theme(legend.position = "top")


figure <- ggarrange(fig2 + rremove("ylab") , 
                    fig3 + rremove("ylab") , 
                    fig1 + rremove("ylab") ,
                    ncol = 1, 
                    heights = c(1, 1, 1))


figure <- annotate_figure(figure,
    left = textGrob("At least y% of time\n", rot = 90, vjust = 0.5, gp = gpar(cex = 1.3)),
    bottom = textGrob("UTCI", gp = gpar(cex = 1.3))
)
figure

