library(RColorBrewer)
library(viridis)
library(colorspace)
library(scico)
library(readxl)
library(reshape2)
library(ggplot2)
library(ggpubr)
library(grid)
library(scales)

# File names
bl_main_save <- TRUE
verbose <- TRUE
spt_path_res <- file.path("res", "res_atrisk", fsep = .Platform$file.sep)
# Input data file, generated by `R-script/tabfig_1_mean_child/ffs_pirecec_tf_mean_child_csv.R`
spn_path <- file.path(spt_path_res, "fig_a_data.csv", fsep = .Platform$file.sep)
dat_lvl_diff_1990_2020 <- read_csv(spn_path)

# diff_2020_1990 <-
# read_excel("c:/users/kaifs/onedrive/documents/dropbox_penn/dropbox/pire/team/kai_feng/cec_results/res_b_childrenatrisk/plot_data.xlsx", sheet = "diff_2020_1990")
# dat1990 <-
# read_excel("C:/Users/Kaifs/OneDrive/Documents/dropbox_penn/Dropbox/PIRE/team/kai_feng/cec_results/res_b_childrenatrisk/plot_data.xlsx", sheet = "1990")
# dat2020 <-
# read_excel("C:/Users/Kaifs/OneDrive/Documents/dropbox_penn/Dropbox/PIRE/team/kai_feng/cec_results/res_b_childrenatrisk/plot_data.xlsx", sheet = "2020")
dat1990 <- dat_lvl_diff_1990_2020 %>%
    filter(stats == "cdf_comp", year == 1990)
dat2020 <- dat_lvl_diff_1990_2020 %>%
    filter(stats == "cdf_comp", year == 2020)
diff_2020_1990 <- dat_lvl_diff_1990_2020 %>%
    filter(stats == "cdf_comp_diff")

diff_2020_1990 <- melt(as.matrix(diff_2020_1990), varnames = c("Row", "Column"))
diff_2020_1990[diff_2020_1990$Row == 1, ]$Row <- 0.1
diff_2020_1990[diff_2020_1990$Row == 2, ]$Row <- 0.2
diff_2020_1990[diff_2020_1990$Row == 3, ]$Row <- 0.3
diff_2020_1990$value <- diff_2020_1990$value * 100
diff_2020_1990$type <- "2020 - 1990"

dat1990 <- melt(as.matrix(dat1990), varnames = c("Row", "Column"))
dat1990[dat1990$Row == 1, ]$Row <- 0.1
dat1990[dat1990$Row == 2, ]$Row <- 0.2
dat1990[dat1990$Row == 3, ]$Row <- 0.3
dat1990$value <- dat1990$value * 100
dat1990$type <- "1990"

dat2020 <- melt(as.matrix(dat2020), varnames = c("Row", "Column"))
dat2020[dat2020$Row == 1, ]$Row <- 0.1
dat2020[dat2020$Row == 2, ]$Row <- 0.2
dat2020[dat2020$Row == 3, ]$Row <- 0.3
dat2020$value <- dat2020$value * 100
dat2020$type <- "2020"

dat <- rbind(diff_2020_1990, dat1990, dat2020)

fig1 <- ggplot(diff_2020_1990 %>% filter(Column > 25), aes(x = Column, y = Row, fill = value)) +
    geom_tile() +
    geom_text(aes(label = sprintf("%.2f%%", value)), size = 8) +
    scale_fill_gradient2(mid = "#FBFEF9", low = "#A63446", high = "#0C6291", breaks = seq(0, 10, 2)) +
    # scale_fill_gradientn(colors = colorRampPalette(brewer.pal(9, "YlOrRd"))(100))+
    # scale_fill_gradientn(colors = rev(sequential_hcl(100,h = c(0, 0))))+
    theme_classic() +
    scale_y_reverse(labels = percent_format(scale = 100)) +
    theme(
        text = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.text.x = element_text(size = 20),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 16)
    ) +
    labs(x = "\nUTCI(\u00B0C)", y = "Minimum Annual Share of Hours\n", fill = "Change in Percentage of Children from 1990 to 2020") +
    theme(legend.position = "") +
    scale_x_continuous(breaks = seq(26, 32, 1))

fig2 <- ggplot(dat1990 %>% filter(Column > 25), aes(x = Column, y = Row, fill = value)) +
    geom_tile() +
    geom_text(aes(label = sprintf("%.2f%%", value)), size = 8) +
    scale_fill_gradient2(mid = "#FBFEF9", low = "#0C6291", high = "#A63446") +
    # scale_fill_gradientn(colors = colorRampPalette(brewer.pal(9, "YlOrRd"))(100))+
    # scale_fill_gradientn(colors = rev(sequential_hcl(100,h = c(0, 0))))+
    theme_classic() +
    scale_y_reverse(labels = percent_format(scale = 100)) +
    theme(
        text = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.text.x = element_text(size = 20),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 16)
    ) +
    labs(x = "UTCI(\u00B0C)", y = "Minimum Annual Share of Children's Hours\n", fill = "Percentage of Children (%)") +
    theme(legend.position = "top") +
    scale_x_continuous(breaks = seq(26, 32, 1))

fig3 <- ggplot(dat2020 %>% filter(Column > 25), aes(x = Column, y = Row, fill = value)) +
    geom_tile() +
    geom_text(aes(label = sprintf("%.2f%%", value)), size = 8) +
    scale_fill_gradient2(mid = "#FBFEF9", low = "#0C6291", high = "#A63446") +
    # scale_fill_gradientn(colors = colorRampPalette(brewer.pal(9, "YlOrRd"))(100))+
    # scale_fill_gradientn(colors = rev(sequential_hcl(100,h = c(0, 0))))+
    theme_classic() +
    scale_y_reverse(labels = percent_format(scale = 100)) +
    theme(
        text = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.text.x = element_text(size = 20),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 16)
    ) +
    labs(x = "UTCI(\u00B0C)", y = "Minimum Annual Share of Children's Hours\n", fill = "Percentage of Children (%)") +
    theme(legend.position = "top") +
    scale_x_continuous(breaks = seq(26, 32, 1))

ggplot(dat, aes(x = Column, y = Row, fill = value)) +
    geom_tile() +
    geom_text(aes(label = sprintf("%.2f%%", value)), size = 4) +
    # scale_fill_gradient2(mid="#FBFEF9",low="#0C6291",high="#A63446") +
    scale_fill_gradientn(colors = colorRampPalette(brewer.pal(9, "YlOrRd"))(100)) +
    # scale_fill_gradientn(colors = rev(sequential_hcl(100,h = c(0, 0))))+
    facet_wrap(~type, scales = "free", ncol = 1) +
    theme_classic() +
    scale_y_reverse() +
    theme(
        # panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        text = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        axis.text.x = element_text(size = 16),
        legend.text = element_text(size = 12)
    ) +
    labs(x = "UTCI", y = "Minimum Annual Share of Children's Hours", fill = "Percentage of Children (%)") +
    theme(legend.position = "top")


figure <- ggarrange(fig2 + rremove("ylab"), fig3 + rremove("ylab"), fig1 + rremove("ylab"),
    ncol = 1,
    labels = c("   1990", "   2020", "2020b1990")
)

figure <- annotate_figure(figure,
    left = textGrob("Minimum Annual Share of Children's Hours\n", rot = 90, vjust = 0.5, gp = gpar(cex = 1.3)),
    bottom = textGrob("UTCI", gp = gpar(cex = 1.3))
)
figure
