# Implement step 2, lower temp, of https://github.com/ClimateInequality/PrjCEC/issues/37
# Input data already in approximately the right structure with the right columns and rows.
# 1. Select three points interval temp levels
# 2. All regions, vs province by region comparisons
# 3. Count by group
# 4. Format columns, decimals, percentage signs, etc
# 5. Generate table, with column names, groupings, and standard code blocks

# load library
library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(kableExtra)

# File names
bl_main_save <- TRUE
verbose <- TRUE
spt_path_res <- file.path("res", "res_region_prov", fsep = .Platform$file.sep)
# Input data file, generated by `R-script/tabfig_1_mean_child/ffs_pirecec_tf_mean_child_csv.R`
spn_path <- file.path(spt_path_res, "tab_a2_moderateheat_data.csv", fsep = .Platform$file.sep)
df_data_tab_a2 <- read_csv(spn_path)
# latex file name for storage
spn_tex_out <- file.path(spt_path_res, "tab_a2_moderateheat.tex", fsep = .Platform$file.sep)

# 1. Select three points interval temp levels: Already selected
# https://utci.lobelia.earth/what-is-utci
# https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10084168/
# https://climate-adapt.eea.europa.eu/en/metadata/indicators/thermal-comfort-indices-universal-thermal-climate-index-1979-2019#:~:text=The%20categories%20relate%20to%20UTCI,%3B%20%2D27%20to%20%2D40%3A
# The categories relate to UTCI values as follows: above +46: extreme heat stress; +38 to +46: very strong heat stress; +32 to +38: strong heat stress; +26 to +32: moderate heat stress; +9 to +26: no thermal stress; +9 to 0: slight cold stress; 0 to -13: moderate cold stress; -13 to -27: strong cold stress; -27 to -40: very strong cold stress; below -40: extreme cold stress.
# 38-46 = very strong heat stress
# 32-38 = strong heat stress
# 26-32 = moderate heat stress
# 0-9 = slight cold stress
# -13-0 = moderate cold stress
# -13--27 = Strong cold stress
# -40--27 = Very strong colde stress
# drop temperatures between 9 and 26 degrees
# upper bound less than
df_data_tab_a2 <- df_data_tab_a2 %>% 
  select(
    loc_level, region_prov_name, 
    contains("23"), contains("26"), contains("29"))

# 2. All regions, vs province by region comparisons
ls_region_prov <- list(
  "Regional" = c(
    "Central", "Eastern", "Northeastern", "Western"
  ),
  "Central" = c(
    "Anhui", "Henan", "Hubei", "Hunan", "Jiangxi", "Shanxi"
  ),
  "Eastern" = c(
    "Beijing", "Fujian", "Guangdong", "Hainan", "Hebei",
    "Jiangsu", "Shandong", "Shanghai", "Tianjin", "Zhejiang"
  ),
  "Northeastern" = c(
    "Heilongjiang", "Jilin", "Liaoning"
  ),
  "Western" = c(
    "Chongqing", "Gansu", "Guangxi", "Guizhou", 
    "Inner Mongolia", "Neimenggu",
    "Ningxia", "Qinghai", "Shaanxi", "Sichuan", 
    "Tibet", "Xizang",
    "Xinjiang", "Yunnan"
  )
)
# Add region_group sorters
df_data_tab_a2_prc <- df_data_tab_a2 %>%
  mutate(region_group_label = case_when(
    region_prov_name %in% ls_region_prov$Regional ~ "Regions",
    region_prov_name %in% ls_region_prov$Central ~ "Central region",
    region_prov_name %in% ls_region_prov$Eastern ~ "Eastern region",
    region_prov_name %in% ls_region_prov$Northeastern ~ "Northeastern region",
    region_prov_name %in% ls_region_prov$Western ~ "Western region"
  )) %>% 
  mutate(region_group_sorter = case_when(
    region_prov_name %in% ls_region_prov$Regional ~ "0Regional",
    region_prov_name %in% ls_region_prov$Central ~ "3Central",
    region_prov_name %in% ls_region_prov$Eastern ~ "1Eastern",
    region_prov_name %in% ls_region_prov$Northeastern ~ "2Northeastern",
    region_prov_name %in% ls_region_prov$Western ~ "4Western"
  )) %>% 
  mutate(prov_group_sorter = case_when(
    region_prov_name == "Central" ~ "3Central",
    region_prov_name == "Eastern" ~ "1Eastern",
    region_prov_name == "Northeastern" ~ "2Northeastern",
    region_prov_name == "Western" ~ "4Western",
    TRUE ~ region_prov_name
  )) %>% 
  select(region_group_sorter, prov_group_sorter, everything())
if (verbose) {
  print(glue::glue("F-780904, S1"))
  print(df_data_tab_a2_prc)
}

# 3. Count by group
df_data_tab_a2_prc <- df_data_tab_a2_prc %>% 
  arrange(region_group_sorter, prov_group_sorter)
# Count by group
df_group_counts <- df_data_tab_a2_prc %>%
  group_by(region_group_sorter, region_group_label) %>%
  arrange(prov_group_sorter, .by_group = TRUE) %>%
  summarize(group_count = n()) %>%
  ungroup() %>%
  mutate(group_count_start = cumsum(group_count) - group_count + 1) %>%
  mutate(group_count_end = cumsum(group_count)) %>%
  select(group_count_start, group_count_end, everything())
if (verbose) {
  print(glue::glue("F-780904, S2"))
  print(df_group_counts)
}

# 4. Format columns, decimals, percentage signs, etc
df_data_tab_a2_format <- df_data_tab_a2_prc %>%
  select(
    -region_group_sorter, -prov_group_sorter,
    -loc_level, -region_group_label
  ) %>%
  mutate(across(
      contains("percent"),
      ~ case_when(
          (.) >= 10 ~ paste0(format(round(./10, 1), nsmall = 1, ), "k%"),
          (.) >= 1 ~ paste0(format(round(., 2) * 100, nsmall = 0), "%"),
          TRUE ~ paste0(format(round(., 2) * 100, nsmall = 0), "%")          
      )
  )) %>%
  mutate_at(
    vars(contains("year")),
    list(~ paste0(
      format(round(., 3) * 100,
        nsmall = 1,
        big.mark = ","
      ),
      "%"
    ))
  ) %>%
  mutate_at(
    vars(contains("percpoint")),
    list(~ paste0(
        format(round(., 3) * 100,
          nsmall = 1,
          big.mark = ","
        ),
        "pp"
    ))
  )
# Replace NAs
df_data_tab_a2_format <- df_data_tab_a2_format %>%
  # mutate(across(starts_with("year"), ~ case_when(. == "0.0%" ~ "", TRUE ~ .))) %>%
  # mutate(across(starts_with("cdf_percent"), ~ case_when(stringr::str_trim(.) == "0%" ~ "", TRUE ~ .))) %>%
  # mutate_at(vars(starts_with("year")), ~ str_replace(., " 0.0%", "")) %>%
  # mutate_at(vars(starts_with("cdf_percpoint")), ~ str_replace(., " 0.0pp", "")) %>%
  # mutate_at(vars(starts_with("cdf_percent")), ~ str_replace(., " 0.0%", "")) %>%
  mutate_at(vars(starts_with("cdf_percpoint")), ~ str_replace(., "NApp", "")) %>%
  mutate_at(vars(starts_with("cdf_percent")), ~ str_replace(., "NA%", "")) %>%
  mutate_at(vars(starts_with("cdf_percent")), ~ str_replace(., "Infk%", "")) %>%
  mutate_at(vars(starts_with("cdf_percent")), ~ str_replace(., "Inf%", ""))

# 5. Generate table, with column names, groupings, and standard code blocks
ar_st_kableformat <- c("html", "latex")
for (st_kableformat in ar_st_kableformat) {
  # Column names
  ar_st_col_names <- c(
    "Location",
    "1990",
    "2020",
    "Level",
    "\\%",
    "1990",
    "2020",
    "Level",
    "\\%",
    "1990",
    "2020",
    "Level",
    "\\%"
  )
  # Define column groups, grouping the names above
  # =1/3/2 are number of columns group title covers
  ar_st_col_groups1 <- c(
    " " = 1,
    "At least borderline thermal stress" = 4,
    "At least moderate heat stress" = 8
  )
  ar_st_col_groups2 <- c(
    " " = 1,
    "$\\ge$ UTCI 23$^{\\circ}C$" = 4,
    "$\\ge$ UTCI 26$^{\\circ}C$" = 4,
    "$\\ge$ UTCI 29$^{\\circ}C$" = 4
  )
  ar_st_col_groups3 <- c(
    " " = 1,
    "Share of time" = 2,
    "Changes" = 2,
    "Share of time" = 2,
    "Changes" = 2,
    "Share of time" = 2,
    "Changes" = 2
  )
  # Second, we construct main table, and add styling.
  bk_tab_a2 <- kbl(
    df_data_tab_a2_format,
    format = st_kableformat,
    label = "app:regionprov:moderateheat",
    # escape = F,
    linesep = "",
    booktabs = T,
    longtable = T,
    align = "c",
    caption = "Regional Average Share of Time at Risk of Exposure to Moderate Heat Stress Thresholds for Children (ages 0-14), 1990 to 2020",
    col.names = ar_st_col_names
  ) %>%
    # see https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html#Bootstrap_table_classes
    kable_styling(
      bootstrap_options = c("striped", "hover", "condensed", "responsive"),
      full_width = F, position = "left"
    )
  # Third, we add in column groups.
  bk_tab_a2 <- bk_tab_a2 %>%
    add_header_above(ar_st_col_groups3) %>%
    add_header_above(ar_st_col_groups2) %>%
    add_header_above(ar_st_col_groups1)
  # Fourth, we add in row groups.
  for (it_group in seq(1, dim(df_group_counts)[1])) {
    # Reion full name info
    st_loc <- as.character(df_group_counts[[it_group, "region_group_label"]])
    # groups start and end
    it_group_count_start <- df_group_counts[[it_group, "group_count_start"]]
    it_group_count_end <- df_group_counts[[it_group, "group_count_end"]]
    # display text
    st_panel_letter <- base::LETTERS[it_group]
    # Heading group row, year
    st_panel_text <- paste0(
      "Panel ", st_panel_letter, ": ", st_loc
    )
    # Add to table
    bk_tab_a2 <- bk_tab_a2 %>%
      pack_rows(
        st_panel_text, it_group_count_start, it_group_count_end,
        latex_gap_space = "0.25em",
        latex_align = "c",
        hline_after = TRUE
      )
  }
  # Fifth, column formatting.
  fl_width_country <- 1.95
  st_width_country <- paste0(fl_width_country, "cm")
  bk_tab_a2 <- bk_tab_a2 %>%
    column_spec(1, width = st_width_country) %>%
    column_spec(c(2,3,5,6,7,9,10,11,13), width = "0.60cm") %>%
    column_spec(c(5,9,13), width = "0.70cm") %>%
    column_spec(c(4,8,12), width = "0.80cm")
  # Final adjustments
  # Headings on all pages, note use `sub` to replace first midrule
  st_headend <- paste0(
    "\\midrule\\endhead\n",
    "\\addlinespace[0.2em]\\hline\\addlinespace[0.2em]\n",
    "\\multicolumn{", dim(df_data_tab_a2_format)[2], "}{r}{\\emph{Continued on next page}}\\\\\n",
    "\\endfoot\\endlastfoot"
  )
  bk_tab_a2 <- sub(bk_tab_a2,
    pattern = "\\midrule", replacement = st_headend,
    fixed = TRUE
  )
  # country-names left-align
  bk_tab_a2 <- gsub(bk_tab_a2,
    pattern = paste0("\\centering\\arraybackslash}p{", st_width_country, "}"),
    replacement = paste0("\\raggedright\\arraybackslash}p{", st_width_country, "}"),
    fixed = TRUE
  )
  bk_tab_a2 <- gsub(bk_tab_a2,
    pattern = paste0("\\$\\textasciicircum{}\\{\\textbackslash{}circ\\}C\\$"),
    replacement = paste0("$^{\\circ}C$"),
    fixed = TRUE
  )
  bk_tab_a2 <- gsub(bk_tab_a2,
    pattern = paste0("\\$\\textbackslash{}ge\\$"),
    replacement = paste0("$\\ge$"),
    fixed = TRUE
  )
  st_text <- ""
  bk_tab_a2 <- gsub(bk_tab_a2,
    pattern = paste0("\\textbackslash{}", st_text, "\\"),
    replacement = paste0("\\", st_text),
    fixed = TRUE
  )
  # midrule replacing hline
  bk_tab_a2 <- gsub(bk_tab_a2,
    pattern = "hline",
    replacement = "midrule", fixed = TRUE
  )

  # 6. Finally, save table content to file
  if (st_kableformat == "latex") {
    if (bl_main_save) {
      fileConn <- file(spn_tex_out)
      writeLines(bk_tab_a2, fileConn)
      close(fileConn)
      if (verbose) {
        print(glue::glue("F-873270, S3"))
        print(glue::glue("Latex saved: {spn_tex_out}"))
      }
    }
  } else if (st_kableformat == "html") {
    print(bk_tab_a2)
  }
}
