# Implement step C of https://github.com/ClimateInequality/PrjCEC/issues/38
# Using existing thresholds grouping structure, from
# `R-script/tabfig_2_decompose/ffs_pirecec_tf_region_prov_tab_a.R`

# load library
library(readr)
library(dplyr)
library(tidyr)
library(kableExtra)

# File names
bl_main_save <- TRUE
verbose <- TRUE
spt_path_res <- file.path("res", "res_decompose", fsep = .Platform$file.sep)
# Input data file, generated by `R-script/tabfig_1_mean_child/ffs_pirecec_tf_mean_child_csv.R`
spn_path <- file.path(spt_path_res, "tab_b_data.csv", fsep = .Platform$file.sep)
df_data_tab_b <- read_csv(spn_path)

# regions to consider, only consider regions with substantive changes
ar_st_regions <- c("Eastern", "Northeastern")

for (st_region in ar_st_regions) {
  # latex file name for storage
  spn_tex_out <- file.path(spt_path_res,
    paste0("tab_b_", tolower(st_region), ".tex"),
    fsep = .Platform$file.sep
  )

  # 1. Get lower and upper bounds for heat severity levels
  # https://utci.lobelia.earth/what-is-utci
  # https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10084168/
  # https://climate-adapt.eea.europa.eu/en/metadata/indicators/thermal-comfort-indices-universal-thermal-climate-index-1979-2019#:~:text=The%20categories%20relate%20to%20UTCI,%3B%20%2D27%20to%20%2D40%3A
  # The categories relate to UTCI values as follows: above +46: extreme heat stress; +38 to +46: very strong heat stress; +32 to +38: strong heat stress; +26 to +32: moderate heat stress; +9 to +26: no thermal stress; +9 to 0: slight cold stress; 0 to -13: moderate cold stress; -13 to -27: strong cold stress; -27 to -40: very strong cold stress; below -40: extreme cold stress.
  # 38-46 = very strong heat stress
  # 32-38 = strong heat stress
  # 26-32 = moderate heat stress
  # 0-9 = slight cold stress
  # -13-0 = moderate cold stress
  # -13--27 = Strong cold stress
  # -40--27 = Very strong colde stress
  # drop temperatures between 9 and 26 degrees
  # upper bound less than
  ls_temp_bounds <- list(
    "Very strong heat stress" = c(3, 38, 46),
    "Strong heat stress" = c(2, 32, 38),
    "Moderate heat stress" = c(1, 26, 32),
    "Slight cold stress" = c(-1, 0, 9),
    "Moderate cold stress" = c(-2, -13, 0),
    "Strong cold stress" = c(-3, -27, -13),
    "Very strong cold stress" = c(-4, -40, -27)
  )
  if (verbose) {
    print(glue::glue("F-928570, S1"))
    print(ls_temp_bounds)
  }

  # 2. Generate heat severity grouping variable
  # Filter out the very strong heat stress due to small gaps
  df_data_tab_b_prc <- df_data_tab_b %>%
    filter(
      region_name == st_region,
      utci_thres >= 20,
      utci_thres <= 37
    ) %>%
    select(-region_name) %>%
    mutate(
      utci_stress_grp_sorter = 0,
      utci_stress_grp = "No thermal stress"
    ) %>%
    select(utci_stress_grp_sorter, utci_stress_grp, utci_thres, everything())
  # temp group names
  ar_st_names <- names(ls_temp_bounds)
  # loop over and replace
  for (it_temp_group in seq(1, length(ar_st_names))) {
    # Get bounds values
    st_grp_name <- ar_st_names[it_temp_group]
    ar_fl_bounds <- ls_temp_bounds[[st_grp_name]]
    it_group_sorter <- ar_fl_bounds[1]
    fl_lower_closed_bound <- ar_fl_bounds[2]
    fl_upper_open_bound <- ar_fl_bounds[3]
    # Update groups
    df_data_tab_b_prc <- df_data_tab_b_prc %>%
      mutate(utci_stress_grp = case_when(
        (utci_thres >= fl_lower_closed_bound) &
          (utci_thres < fl_upper_open_bound) ~ st_grp_name,
        TRUE ~ utci_stress_grp
      )) %>%
      mutate(utci_stress_grp_sorter = case_when(
        utci_stress_grp == st_grp_name ~ it_group_sorter,
        TRUE ~ utci_stress_grp_sorter
      ))
    if (verbose) {
      print(glue::glue("F-928570, S2"))
      print(st_grp_name)
      print(fl_lower_closed_bound)
      print(fl_upper_open_bound)
      print(
        df_data_tab_b_prc %>%
          group_by(
            utci_stress_grp_sorter,
            utci_stress_grp
          ) %>% tally()
      )
    }
  }

  # 3. Count by group
  # Sorted file
  df_data_tab_b_sorted <- df_data_tab_b_prc %>%
    arrange(
      desc(utci_stress_grp_sorter), desc(utci_thres),
    ) %>%
    group_by(utci_stress_grp_sorter) %>%
    ungroup()
  # Count by group
  df_group_counts <- df_data_tab_b_sorted %>%
    group_by(utci_stress_grp, utci_stress_grp_sorter) %>%
    summarize(group_count = n()) %>%
    arrange(desc(utci_stress_grp_sorter)) %>%
    ungroup() %>%
    mutate(group_count_start = cumsum(group_count) - group_count + 1) %>%
    mutate(group_count_end = cumsum(group_count)) %>%
    select(group_count_start, group_count_end, everything())

  # 4. Format columns, decimals, percentage signs, etc
  df_data_tab_b_format <- df_data_tab_b_sorted %>%
    select(-utci_stress_grp_sorter, -utci_stress_grp) %>%
    mutate_at(
      vars(contains("utci_thres")),
      list(~ paste0(
        "$\\ge$ ",
        format(round(., 0), nsmall = 0),
        " $^{\\circ}C$"
      ))
    ) %>%
    mutate_at(
      vars(contains("yt_")),
      list(~ ifelse(abs(.) <= 0.01,
        paste0(
          formatC(. * 100,
            digits = 1,
            format = "fg",
            flag = "#"
          ),
          "%"
        ),
        paste0(
          format(round(., 3) * 100,
            nsmall = 1,
            big.mark = ","
          ),
          "%"
        )
      ))
    ) %>%
    mutate_at(
      vars(contains("percent")),
      list(~ paste0(
        format(round(., 2) * 100,
          nsmall = 0,
          big.mark = ","
        ),
        "%"
      ))
    ) %>%
    mutate_at(
      vars(contains("percpoint")),
      list(~ ifelse(abs(.) <= 0.0001,
        paste0(
          formatC(. * 100,
            digits = 1,
            format = "fg",
            drop0trailing = T,
            flag = "#"
          ),
          "pp"
        ),
        paste0(
          format(round(., 4) * 100,
            nsmall = 2,
            big.mark = ","
          ),
          "pp"
        )
      ))
    )

  # 5. Generate table, with column names, groupings, and standard code blocks
  ar_st_kableformat <- c("html", "latex")
  for (st_kableformat in ar_st_kableformat) {
    # Column names
    ar_st_col_names <- c(
      "UTCI thresholds",
      "1990",
      "2020",
      "$\\Delta$",
      "Prediction",
      "Vs. 1990",
      "\\% of $\\Delta$",
      "Prediction",
      "Vs. 1990",
      "\\% of $\\Delta$"
    )
    # Define column groups, grouping the names above
    # =1/3/2 are number of columns group title covers
    ar_st_col_groups1 <- c(
      " " = 1,
      "Actual 2020 vs 1990" = 3,
      "2020 UTCI with 1990 population" = 3,
      "1990 UTCI with 2020 population" = 3
    )
    ar_st_col_groups2 <- c(
      " " = 1,
      "Share of time" = 2,
      "Changes" = 1,
      "Share-time" = 1,
      "Decompose changes" = 2,
      "Share-time" = 1,
      "Decompose changes" = 2
    )
    # Second, we construct main table, and add styling.
    st_caption <- paste0(
      st_region,
      ": decompose changes in average heat exposure for children (ages 0--14)"
    )
    bk_tab_b <- kbl(
      df_data_tab_b_format,
      format = st_kableformat,
      # escape = F,
      linesep = "",
      booktabs = T,
      longtable = T,
      align = "c",
      caption = st_caption,
      col.names = ar_st_col_names
    ) %>%
      # see https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html#Bootstrap_table_classes
      kable_styling(
        bootstrap_options = c("striped", "hover", "condensed", "responsive"),
        full_width = F, position = "left"
      )
    # Third, we add in column groups.
    bk_tab_b <- bk_tab_b %>%
      add_header_above(ar_st_col_groups2) %>%
      add_header_above(ar_st_col_groups1)
    # Fourth, we add in row groups.
    for (it_group in seq(1, dim(df_group_counts)[1])) {
      # Reion full name info
      st_loc <- as.character(df_group_counts[[it_group, "utci_stress_grp"]])
      # groups start and end
      it_group_count_start <- df_group_counts[[it_group, "group_count_start"]]
      it_group_count_end <- df_group_counts[[it_group, "group_count_end"]]
      # Add to table
      bk_tab_b <- bk_tab_b %>%
        pack_rows(
          st_loc, it_group_count_start, it_group_count_end,
          latex_gap_space = "1em",
          latex_align = "c",
          hline_after = TRUE
        )
    }
    # Fifth, column formatting.
    fl_width_country <- 2.1
    st_width_country <- paste0(fl_width_country, "cm")
    bk_tab_b <- bk_tab_b %>%
      column_spec(1, width = st_width_country) %>%
      column_spec(c(2, 3, 4), width = "1.0cm") %>%
      column_spec(c(7, 10), width = "1.0cm") %>%
      column_spec(c(5, 6, 8, 9), width = "1.1cm")
    # Final adjustments
    # Headings on all pages, note use `sub` to replace first midrule
    st_headend <- paste0(
      "\\midrule\\endhead\n",
      "\\addlinespace[0.2em]\\hline\\addlinespace[0.2em]\n",
      "\\multicolumn{", dim(df_data_tab_b_format)[2], "}{r}{\\emph{Continued on next page}}\\\\\n",
      "\\endfoot\\endlastfoot"
    )
    bk_tab_b <- sub(bk_tab_b,
      pattern = "\\midrule", replacement = st_headend,
      fixed = TRUE
    )
    # country-names left-align
    bk_tab_b <- gsub(bk_tab_b,
      pattern = paste0("\\centering\\arraybackslash}p{", st_width_country, "}"),
      replacement = paste0("\\raggedright\\arraybackslash}p{", st_width_country, "}"),
      fixed = TRUE
    )
    bk_tab_b <- gsub(bk_tab_b,
      pattern = paste0("\\$\\textasciicircum{}\\{\\textbackslash{}circ\\}C\\$"),
      replacement = paste0("$^{\\circ}C$"),
      fixed = TRUE
    )
    bk_tab_b <- gsub(bk_tab_b,
      pattern = paste0("\\$\\textbackslash{}Delta\\$"),
      replacement = paste0("$\\Delta$"),
      fixed = TRUE
    )
    bk_tab_b <- gsub(bk_tab_b,
      pattern = paste0("\\$\\textbackslash{}ge\\$"),
      replacement = paste0("$\\ge$"),
      fixed = TRUE
    )
    st_text <- ""
    bk_tab_b <- gsub(bk_tab_b,
      pattern = paste0("\\textbackslash{}", st_text, "\\"),
      replacement = paste0("\\", st_text),
      fixed = TRUE
    )
    # midrule replacing hline
    bk_tab_b <- gsub(bk_tab_b,
      pattern = "hline",
      replacement = "midrule", fixed = TRUE
    )

    # 6. Finally, save table content to file
    if (st_kableformat == "latex") {
      if (bl_main_save) {
        fileConn <- file(spn_tex_out)
        writeLines(bk_tab_b, fileConn)
        close(fileConn)
        if (verbose) {
          print(glue::glue("F-928570, S3"))
          print(glue::glue("Latex saved: {spn_tex_out}"))
        }
      }
    } else if (st_kableformat == "html") {
      print(bk_tab_b)
    }
  }
}
